const SearchActionTypes = {
	SET_SEARCH_RESULT           : 'SET_SEARCH_RESULT',
	FETCH_SEARCH_RESULT_START   : 'FETCH_SEARCH_RESULT_START',
	FETCH_SEARCH_RESULT_SUCCESS : 'FETCH_SEARCH_RESULT_SUCCESS',
	FETCH_SEARCH_RESULT_FAILURE : 'FETCH_SEARCH_RESULT_FAILURE',
	SET_QUERY                   : 'SET_QUERY'
};

export default SearchActionTypes;
